apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
      - name: api
        image: weather-api:1.0
        imagePullPolicy: Never
        ports:
            - nodePort: 18080  # Matches kind-cluster.yaml
            - containerPort: 8080
        port: 80
        targetPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "host.docker.internal:9092"
        - name: MONGODB_URI
          value: "mongodb://mongodb-0.mongodb,mongodb-1.mongodb,mongodb-2.mongodb/weather"
