apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-stream
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-stream
  template:
    metadata:
      labels:
        app: weather-stream
    spec:
      containers:
      - name: stream
        image: weather-stream:1.5
        imagePullPolicy: Never
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "host.docker.internal:9092"